import type { ReactNode } from "react";
import { PrismInput, PrismTextarea, PrismSelect } from "./prism-field";
import { PrismMultiSelect, PrismDateRange, PrismRadioGroup } from "./prism-selection";
import { PrismSwitch, PrismFileDropzone } from "./prism-utility";
import { PrismTag, PrismChip } from "./prism-badge";
import { PrismOutline } from "./prism-profile";
import { PrismButton } from "./prism-button";
import { PrismAiGenerateButton } from "./prism-management";
import { PrismContextOptionCard } from "./prism-context";
import type { PrismAttachment } from "./prism-admin";

export type PrismFormActions = { onSubmit: () => void; onCancel: () => void; onDelete?: () => void; busy?: boolean; readOnly?: boolean; submitLabel?: string; error?: string };
function Actions({onSubmit,onCancel,onDelete,busy,readOnly,submitLabel="등록",error,valid}:PrismFormActions & {valid:boolean}) {
    return <>{error && <p role="alert" className="prism-error">{error}</p>}<footer className="prism-domain-form-actions"><div><PrismButton variant="line" onClick={onCancel} disabled={busy}>취소</PrismButton>{onDelete && !readOnly && <PrismButton variant="line" onClick={onDelete} disabled={busy}>삭제</PrismButton>}</div>{!readOnly && <PrismButton type="submit" disabled={!valid || busy} aria-busy={busy}>{busy ? "저장 중" : submitLabel}</PrismButton>}</footer></>;
}
export type PrismNoticeDraft = {title:string;content:string;allCompanies:boolean;companyIds:readonly string[];popup:boolean;start:string|null;end:string|null};
export function PrismNoticeForm({value,onValueChange,companies,files,onFilesSelected,onRemoveFile,canChooseAllCompanies,canEdit=true,...actions}:PrismFormActions & {
    value:PrismNoticeDraft;onValueChange:(value:PrismNoticeDraft)=>void;companies:readonly {value:string;label:string}[]; files:readonly PrismAttachment[];
    onFilesSelected:(files:File[])=>void;onRemoveFile?:(id:string)=>void;canChooseAllCompanies?:boolean;canEdit?:boolean;
}) {
    const locked=actions.readOnly || !canEdit; const valid=!!value.title.trim()&&!!value.content.trim()&&(value.allCompanies || !!value.companyIds.length)&&(!value.popup || (!!value.start&&!!value.end&&value.start<=value.end));
    const update=(next:Partial<PrismNoticeDraft>)=>onValueChange({...value,...next});
    return <form className="prism-domain-form" onSubmit={e=>{e.preventDefault();if(valid&&!locked&&!actions.busy)actions.onSubmit();}}><h3>공지사항 {actions.submitLabel==="수정" ? "상세" : "등록"}</h3>
        <PrismOutline title="공지 내용"><PrismInput label="제목" value={value.title} required readOnly={locked} disabled={actions.busy} onChange={e=>update({title:e.target.value})}/><PrismTextarea label="본문" rows={15} value={value.content} required readOnly={locked} disabled={actions.busy} onChange={e=>update({content:e.target.value})}/><PrismFileDropzone label="첨부파일" files={files} onFilesSelected={onFilesSelected} onRemove={locked ? undefined : onRemoveFile} disabled={locked||actions.busy}/></PrismOutline>
        <PrismOutline title="노출 설정"><p className="prism-help">선택한 회사의 사용자에게 공지사항이 노출됩니다.</p><div className="prism-domain-form-row">{canChooseAllCompanies && <PrismSwitch label="전체 회사" checked={value.allCompanies} disabled={locked||actions.busy} onCheckedChange={allCompanies=>update({allCompanies})}/>}<PrismMultiSelect label="노출 범위" options={companies} value={value.companyIds} onValueChange={companyIds=>update({companyIds})} allToggleClearsSelection disabled={locked||actions.busy||value.allCompanies}/></div>
        <hr/><PrismSwitch label="팝업 노출" checked={value.popup} disabled={locked||actions.busy} onCheckedChange={popup=>update(popup ? {popup} : {popup,start:null,end:null})}/><p className="prism-help">서비스 메인 화면에 팝업으로 표시합니다.</p><PrismDateRange label="게시기간" start={value.start} end={value.end} onValueChange={update} disabled={!value.popup||locked||actions.busy}/></PrismOutline>
        {!canEdit && <p role="status">조회만 가능합니다.</p>}<Actions {...actions} readOnly={locked} valid={valid}/></form>;
}
export type PrismCompanyGroupDraft={name:string;companyIds:readonly string[]};
export function PrismCompanyGroupForm({value,onValueChange,companies,nameStatus="idle",onCheckName,detail,onToggleStatus,...actions}:PrismFormActions & {
    value:PrismCompanyGroupDraft;onValueChange:(value:PrismCompanyGroupDraft)=>void;companies:readonly {value:string;label:string}[];nameStatus?:"idle"|"checking"|"available"|"duplicate";onCheckName?:()=>void;
    detail?:{status:string;registrant:string;createdAt:string;updatedAt:string|null};onToggleStatus?:()=>void;
}) {
    const valid=!!value.name.trim()&&!!value.companyIds.length&&nameStatus!=="duplicate"&&nameStatus!=="checking"&&(!onCheckName||nameStatus==="available");
    return <form className="prism-domain-form" onSubmit={e=>{e.preventDefault();if(valid&&!actions.busy&&!actions.readOnly)actions.onSubmit();}}>{detail && <PrismOutline title="등록 정보"><PrismInput label="등록자" value={detail.registrant} readOnly/><div className="prism-domain-form-row"><PrismInput label="등록일" value={detail.createdAt} readOnly/><PrismInput label="최근 수정일" value={detail.updatedAt??"-"} readOnly/></div></PrismOutline>}
        <PrismOutline title="회사 그룹"><div className="prism-domain-form-row"><PrismInput label="회사 그룹명" required value={value.name} disabled={actions.busy} readOnly={actions.readOnly} onChange={e=>onValueChange({...value,name:e.target.value})} onBlur={onCheckName} error={nameStatus==="duplicate" ? "이미 등록된 회사 그룹명입니다." : undefined}/>{detail && <PrismChip color={detail.status==="활성" ? "#40C057" : "#626A75"}>{detail.status}</PrismChip>}</div>
        <hr/><PrismMultiSelect label="회사 선택" options={companies} value={value.companyIds} onValueChange={companyIds=>onValueChange({...value,companyIds})} disabled={actions.busy} readOnly={actions.readOnly}/><div className="prism-domain-company-box"><span>총 {value.companyIds.length}개</span><div>{value.companyIds.map(id=><PrismTag key={id} label={companies.find(c=>c.value===id)?.label??id} onRemove={actions.readOnly||actions.busy ? undefined : ()=>onValueChange({...value,companyIds:value.companyIds.filter(c=>c!==id)})}>{companies.find(c=>c.value===id)?.label??id}</PrismTag>)}</div>{!value.companyIds.length && <p>회사 그룹에 포함할 회사를 선택해 주세요.</p>}</div></PrismOutline>
        {onToggleStatus && <PrismButton variant="line" disabled={actions.busy||actions.readOnly} onClick={onToggleStatus}>{detail?.status==="활성" ? "비활성" : "활성"}</PrismButton>}<Actions {...actions} valid={valid}/></form>;
}
export type PrismUserDraft={email:string;roleId:string;companyGroupId:string};
export function PrismUserForm({value,onValueChange,roles,companyGroups,emailStatus="idle",onCheckEmail,detail,onToggleStatus,...actions}:PrismFormActions & {
    value:PrismUserDraft;onValueChange:(value:PrismUserDraft)=>void;roles:readonly {value:string;label:string;needsCompanyGroup?:boolean}[];
    companyGroups:readonly {id:string;name:string;companies:readonly string[]}[];emailStatus?:"idle"|"checking"|"available"|"invalid"|"duplicate";onCheckEmail?:()=>void;
    detail?:{status:string;name:string;company:string;division:string;employeeNo:string};onToggleStatus?:()=>void;
}) {
    const role=roles.find(r=>r.value===value.roleId); const selected=companyGroups.find(g=>g.id===value.companyGroupId);
    const valid=!!role&&!!value.email.trim()&&emailStatus!=="invalid"&&emailStatus!=="duplicate"&&emailStatus!=="checking"&&(!onCheckEmail||!!detail||emailStatus==="available")&&(!role?.needsCompanyGroup||!!selected);
    return <form className="prism-domain-form" onSubmit={e=>{e.preventDefault();if(valid&&!actions.busy&&!actions.readOnly)actions.onSubmit();}}><PrismOutline title="기본 정보"><div className="prism-domain-form-row"><PrismInput label="이메일 (로그인 ID)" type="email" required value={value.email} readOnly={actions.readOnly||!!detail} disabled={actions.busy} onChange={e=>onValueChange({...value,email:e.target.value})} onBlur={onCheckEmail} error={emailStatus==="invalid" ? "올바른 이메일 형식으로 입력해 주세요." : emailStatus==="duplicate" ? "이미 등록된 이메일 주소입니다." : undefined}/>{detail && <PrismChip color={detail.status==="활성" ? "#40C057" : "#626A75"}>{detail.status}</PrismChip>}</div>
        {detail ? <div className="prism-domain-form-grid">{[["이름",detail.name],["소속 회사",detail.company],["본부/팀",detail.division],["사번",detail.employeeNo]].map(([label,text])=><PrismInput key={label} label={label} value={text} readOnly/>)}</div> : <p className="prism-help">이름 · 소속 회사 · 본부/팀 · 사번은 사용자 등록 후 반영됩니다.</p>}</PrismOutline>
        <PrismOutline title="Role"><PrismRadioGroup label="Role" options={roles} value={value.roleId} disabled={actions.busy||actions.readOnly} onValueChange={roleId=>onValueChange({...value,roleId,companyGroupId:roles.find(r=>r.value===roleId)?.needsCompanyGroup ? value.companyGroupId : ""})}/><hr/>
            {role?.needsCompanyGroup ? <><PrismSelect label="회사 그룹" value={value.companyGroupId} options={companyGroups.map(g=>({value:g.id,label:g.name}))} disabled={actions.busy||actions.readOnly} onValueChange={companyGroupId=>onValueChange({...value,companyGroupId})}/><div className="prism-domain-company-box"><span>총 {selected?.companies.length??0}개</span><div>{selected?.companies.map(company=><PrismTag key={company}>{company}</PrismTag>)}</div></div><p className="prism-help">회사 그룹 관리에서 회사 그룹을 생성·수정할 수 있습니다.</p></> : <p className="prism-help">이 역할은 별도의 회사 그룹 설정이 필요하지 않습니다.</p>}</PrismOutline>
        {onToggleStatus && <PrismButton variant="line" disabled={actions.busy||actions.readOnly} onClick={onToggleStatus}>{detail?.status==="활성" ? "비활성" : "활성"}</PrismButton>}<Actions {...actions} valid={valid}/></form>;
}
export type PrismPositionDraft={name:string;companyId:string;industryId:string;roleId:string;mainJobId:string;subJobId:string;isCore:boolean;context:string;definition:string;expertise:string;experience:string;subExpertise:string;subExperience:string;expertiseIds:readonly string[];experienceIds:readonly string[]};
export function PrismPositionForm({value,onValueChange,companies,industries,roles,jobs,expertiseOptions,experienceOptions,canEditCore,companyContext,onCompanyContext,onGenerate,generating,...actions}:PrismFormActions & {
    value:PrismPositionDraft;onValueChange:(value:PrismPositionDraft)=>void;companies:readonly {value:string;label:string}[];industries:readonly {value:string;label:string}[];roles:readonly {value:string;label:string}[];jobs:readonly {value:string;label:string}[];
    expertiseOptions:readonly {id:string;label:string;description:string}[];experienceOptions:readonly {id:string;label:string;description:string}[];canEditCore?:boolean;companyContext?:ReactNode;onCompanyContext?:()=>void;onGenerate?:(section:"definition"|"experience")=>void;generating?:"definition"|"experience"|null;
}) {
    const locked=actions.readOnly||actions.busy||!!generating; const update=(next:Partial<PrismPositionDraft>)=>onValueChange({...value,...next});
    const duplicate=!!value.subJobId&&value.mainJobId===value.subJobId; const valid=!!value.name.trim()&&!!value.companyId&&!!value.industryId&&!!value.roleId&&!!value.mainJobId&&!duplicate;
    return <form className="prism-domain-form" onSubmit={e=>{e.preventDefault();if(valid&&!locked)actions.onSubmit();}}><h3>포지션 {actions.readOnly||actions.submitLabel==="수정" ? "상세" : "등록"}</h3><PrismOutline title="포지션 기본 정보"><PrismSelect label="회사" value={value.companyId} options={companies} onValueChange={companyId=>update({companyId})} disabled={locked}/><div className="prism-domain-form-grid"><PrismInput label="포지션 명" value={value.name} required onChange={e=>update({name:e.target.value})} disabled={locked}/><PrismSwitch label="핵심 포지션" checked={value.isCore} onCheckedChange={isCore=>update({isCore})} disabled={locked||!canEditCore}/><PrismSelect label="산업" value={value.industryId} options={industries} disabled={locked} onValueChange={industryId=>update({industryId})}/><PrismSelect label="역할" value={value.roleId} options={roles} disabled={locked} onValueChange={roleId=>update({roleId})}/><PrismSelect label="주 직무" value={value.mainJobId} options={jobs} disabled={locked} onValueChange={mainJobId=>update({mainJobId})}/><PrismSelect label="부 직무" value={value.subJobId} options={[{value:"",label:"선택 안 함"},...jobs]} disabled={locked} error={duplicate ? "이미 선택된 직무입니다. 다른 직무를 선택해 주세요." : undefined} onValueChange={subJobId=>update({subJobId})}/></div></PrismOutline>
        <PrismOutline title="Business Context" actions={onCompanyContext && <PrismButton variant="line" size="small" onClick={onCompanyContext}>회사 Task 확인</PrismButton>}>{companyContext}<PrismTextarea label="Business Context" value={value.context} onChange={e=>update({context:e.target.value})} disabled={locked}/></PrismOutline>
        <PrismOutline title="포지션 정의" actions={onGenerate && <PrismAiGenerateButton label="정의 생성" busy={generating==="definition"} disabled={locked} onGenerate={()=>onGenerate("definition")}/>}><PrismTextarea label="Mission" value={value.definition} onChange={e=>update({definition:e.target.value})} disabled={locked}/></PrismOutline>
        <PrismOutline title="요구 역량" actions={onGenerate && <PrismAiGenerateButton label="경험 생성" busy={generating==="experience"} disabled={locked} onGenerate={()=>onGenerate("experience")}/>}><h4>전문성 · 최대 3개</h4><div className="prism-domain-form-grid">{expertiseOptions.map(o=><PrismContextOptionCard key={o.id} option={{value:o.id,label:o.label,description:o.description}} checked={value.expertiseIds.includes(o.id)} disabled={locked||(!value.expertiseIds.includes(o.id)&&value.expertiseIds.length>=3)} onCheckedChange={checked=>update({expertiseIds:checked ? [...value.expertiseIds,o.id] : value.expertiseIds.filter(id=>id!==o.id)})}/>)}</div><h4>성공경험 · 최대 2개</h4><div className="prism-domain-form-grid">{experienceOptions.map(o=><PrismContextOptionCard key={o.id} option={{value:o.id,label:o.label,description:o.description}} checked={value.experienceIds.includes(o.id)} disabled={locked||(!value.experienceIds.includes(o.id)&&value.experienceIds.length>=2)} onCheckedChange={checked=>update({experienceIds:checked ? [...value.experienceIds,o.id] : value.experienceIds.filter(id=>id!==o.id)})}/>)}</div>
        <div className="prism-domain-form-grid">{([['expertise','주 직무 전문성'],['experience','주 직무 성공경험'],...(value.subJobId ? [['subExpertise','부 직무 전문성'],['subExperience','부 직무 성공경험']] : [])] as ["expertise"|"experience"|"subExpertise"|"subExperience",string][]).map(([key,label])=><PrismTextarea key={key} label={label} value={value[key]} onChange={e=>update({[key]:e.target.value})} disabled={locked}/>)}</div></PrismOutline>{generating && <p role="status">요구 사항을 생성하는 중입니다.</p>}<Actions {...actions} busy={actions.busy||!!generating} valid={valid}/></form>;
}
